name: Bug report
about: Report a problem or unexpected behavior in the Electron Multi-Window app
labels: bug
assignees: ''

---

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. ...
2. ...
3. ...

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots or Console Logs**
If applicable, add screenshots or paste relevant error logs from the Electron console to help explain your problem.

**Environment (please complete the following information):**
 - OS: [e.g. Windows 11, macOS Sonoma]
 - Electron version: [e.g. 28.1.0]
 - Node.js version: [e.g. 20.11.0]
 - App version/branch: [e.g. main, pure-electron]

**Additional context**
Add any other context about the problem here (e.g. steps tried, related issues, etc).
