name: Feature request
about: Suggest an improvement or new feature for the Electron Multi-Window app
labels: enhancement
assignees: ''

---

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen in the app.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context, screenshots, or use cases for this feature request. If it relates to Electron, multi-window, or synchronization, please specify.
